/**
 * Generates expanded idioms.json (~500 items).
 * Run: node scripts/generate-idioms.mjs
 */
import { writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));

const classifications = [
  {
    id: "verb",
    labelJa: "動詞別",
    labelEn: "By verb",
    emoji: "🏃",
    descriptionJa: "get・take など動詞ごとにまとめる",
  },
  {
    id: "preposition",
    labelJa: "前置詞別",
    labelEn: "By preposition",
    emoji: "📍",
    descriptionJa: "in・on など前置詞ごとにまとめる",
  },
  {
    id: "other",
    labelJa: "その他の表現",
    labelEn: "Other expressions",
    emoji: "💬",
    descriptionJa: "as句・時間表現・体の慣用句など",
  },
];

/** @type {{id:string,classificationId:string,labelJa:string,headWord:string,emoji:string,coreImage:string,items:[string,string,string,string][]}[]} */
const GROUP_DEFS = [
  // —— verb ——
  {
    id: "get", classificationId: "verb", labelJa: "get 編", headWord: "get", emoji: "📗",
    coreImage: "ある状態になる・何かを得る",
    items: [
      ["get up", "起きる", "I get up at seven every morning.", "私は毎朝7時に起きます。"],
      ["get on", "乗る・うまくいく", "She got on the bus at the station.", "彼女は駅でバスに乗った。"],
      ["get off", "降りる・休む", "Please get off at the next stop.", "次の停留所で降りてください。"],
      ["get over", "克服する", "It took him a while to get over the cold.", "彼が風邪を治すのにしばらくかかった。"],
      ["get along", "うまくやる", "Do you get along with your coworkers?", "同僚とうまくやっていますか？"],
      ["get away", "逃げる・休暇を取る", "We need to get away for the weekend.", "週末はどこかに出かけたい。"],
      ["get back", "戻る・取り戻す", "I'll get back to you tomorrow.", "明日また連絡します。"],
      ["get through", "切り抜ける・連絡がつく", "I couldn't get through to her on the phone.", "電話で彼女に連絡がつかなかった。"],
      ["get rid of", "取り除く", "I want to get rid of these old clothes.", "この古い服を処分したい。"],
      ["get used to", "～に慣れる", "You'll get used to the new schedule soon.", "すぐに新しいスケジュールに慣れるよ。"],
      ["get in", "入る・到着する", "What time did you get in last night?", "昨夜は何時に帰ったの？"],
      ["get out", "出る・明らかになる", "Get out of the car carefully.", "車から気をつけて出て。"],
      ["get across", "伝える", "I couldn't get my point across.", "言いたいことがうまく伝わらなかった。"],
      ["get around", "動き回る・回避する", "It's easy to get around the city by bike.", "この街は自転車で動きやすい。"],
      ["get by", "どうにかやっていく", "We can get by with a little money.", "少しのお金でどうにかやっていける。"],
      ["get down", "下ろす・落ち込む", "Don't let the news get you down.", "そのニュースで落ち込まないで。"],
      ["get into", "ハマる・入る", "She got into photography last year.", "彼女は去年写真にハマった。"],
      ["get out of", "免れる", "He tried to get out of doing homework.", "彼は宿題を逃れようとした。"],
      ["get together", "集まる", "Let's get together this weekend.", "今週末集まろう。"],
      ["get ahead", "出世する・先へ進む", "She works hard to get ahead.", "彼女は出世しようと頑張っている。"],
    ],
  },
  {
    id: "take", classificationId: "verb", labelJa: "take 編", headWord: "take", emoji: "📘",
    coreImage: "手に取る・連れていく・時間などを要する",
    items: [
      ["take off", "離陸する・脱ぐ", "The plane will take off in ten minutes.", "飛行機は10分後に離陸します。"],
      ["take on", "引き受ける・雇う", "She decided to take on a new project.", "彼女は新しいプロジェクトを引き受けることにした。"],
      ["take over", "引き継ぐ", "Who will take over when he retires?", "彼が引退したら誰が引き継ぐの？"],
      ["take up", "始める・占める", "He took up tennis last year.", "彼は去年テニスを始めた。"],
      ["take out", "取り出す・連れ出す", "Let's take out the trash.", "ゴミを出そう。"],
      ["take back", "取り戻す・言い直す", "I take back what I said.", "さっき言ったことは取り消します。"],
      ["take care of", "世話をする", "Can you take care of my dog this weekend?", "今週末うちの犬の世話をしてくれる？"],
      ["take part in", "参加する", "Many students took part in the contest.", "多くの生徒がコンテストに参加した。"],
      ["take after", "似る", "She takes after her mother.", "彼女は母親に似ている。"],
      ["take in", "理解する・騙す・取り入れる", "I couldn't take in all the information.", "情報を全部理解できなかった。"],
      ["take down", "書き取る・取り外す", "Please take down these notes.", "このメモを書き取ってください。"],
      ["take for", "〜だと勘違いする", "Do you take me for a fool?", "バカだと思っているの？"],
      ["take place", "行われる", "The meeting will take place tomorrow.", "会議は明日行われます。"],
      ["take turns", "交代する", "We took turns driving.", "交代で運転した。"],
      ["take advantage of", "利用する", "Take advantage of this opportunity.", "この機会を利用して。"],
      ["take it easy", "気楽にする", "You should take it easy today.", "今日はのんびりした方がいいよ。"],
      ["take into account", "考慮に入れる", "We must take costs into account.", "費用を考慮に入れなければならない。"],
      ["take for granted", "当たり前と思う", "Don't take your parents for granted.", "親を当たり前だと思わないで。"],
      ["take a break", "休憩する", "Let's take a break.", "休憩しよう。"],
      ["take a look", "見てみる", "Take a look at this picture.", "この写真を見てみて。"],
    ],
  },
  {
    id: "make", classificationId: "verb", labelJa: "make 編", headWord: "make", emoji: "📙",
    coreImage: "作る・〜の状態にする",
    items: [
      ["make up", "構成する・仲直りする", "Women make up half of the team.", "チームの半分は女性で構成されている。"],
      ["make out", "理解する・うまくいく", "I can't make out what he's saying.", "彼が何を言っているのか聞き取れない。"],
      ["make for", "〜に向かう・役立つ", "We made for the exit when the alarm rang.", "アラームが鳴ると私たちは出口へ向かった。"],
      ["make sure", "確かめる", "Make sure you lock the door.", "ドアに鍵をかけるのを忘れないで。"],
      ["make up for", "埋め合わせる", "I'll make up for the lost time.", "失った時間を取り戻すよ。"],
      ["make do with", "間に合わせる", "We'll make do with what we have.", "あるもので間に合わせよう。"],
      ["make sense", "意味をなす", "That doesn't make sense.", "それは筋が通らない。"],
      ["make a decision", "決断する", "It's time to make a decision.", "決断の時だ。"],
      ["make a difference", "違いを生む", "Your help made a difference.", "あなたの助けが違いを生んだ。"],
      ["make friends", "友達になる", "It's easy to make friends here.", "ここでは友達を作りやすい。"],
      ["make fun of", "からかう", "Don't make fun of others.", "人をからかわないで。"],
      ["make progress", "進歩する", "She is making progress in English.", "彼女は英語で上達している。"],
      ["make room", "場所を空ける", "Can you make room for one more?", "もう一人分の場所を空けられる？"],
      ["make the most of", "最大限に活かす", "Make the most of your vacation.", "休暇を最大限に活かして。"],
      ["make ends meet", "収支を合わせる", "It's hard to make ends meet.", "収支を合わせるのが大変だ。"],
      ["make it", "間に合う・成功する", "We made it to the station on time.", "時間通りに駅に着けた。"],
      ["make up one's mind", "決心する", "Have you made up your mind?", "決心はついた？"],
      ["make a living", "生計を立てる", "He makes a living as a writer.", "彼は作家として生計を立てている。"],
      ["make an effort", "努力する", "Please make an effort to arrive early.", "早めに着くよう努力してください。"],
      ["make clear", "はっきりさせる", "Let me make this clear.", "はっきり言わせてください。"],
    ],
  },
  {
    id: "put", classificationId: "verb", labelJa: "put 編", headWord: "put", emoji: "📕",
    coreImage: "置く・ある状態に移す",
    items: [
      ["put on", "着る・つける", "Put on your coat. It's cold.", "コートを着て。寒いよ。"],
      ["put off", "延期する", "We put off the meeting until Friday.", "会議を金曜まで延期した。"],
      ["put out", "消す・出す", "Please put out the fire.", "火を消してください。"],
      ["put up with", "我慢する", "I can't put up with the noise.", "この騒音には耐えられない。"],
      ["put away", "しまう", "Put away your toys.", "おもちゃをしまいなさい。"],
      ["put down", "置く・批判する", "Put down your bags here.", "荷物はここに置いて。"],
      ["put forward", "提案する", "She put forward a new idea.", "彼女は新しい案を出した。"],
      ["put together", "組み立てる", "They put together a great team.", "彼らは素晴らしいチームを編成した。"],
      ["put through", "電話をつなぐ・やり遂げる", "Can you put me through to Mr. Lee?", "リーさんにつないでもらえますか？"],
      ["put aside", "取っておく", "Put aside some money each month.", "毎月少しお金を取っておいて。"],
      ["put back", "戻す・遅らせる", "Please put the book back on the shelf.", "本を棚に戻してください。"],
      ["put into", "注ぎ込む", "He puts a lot of effort into his work.", "彼は仕事に多くの努力を注いでいる。"],
      ["put up", "建てる・泊める", "They put up a new building.", "彼らは新しい建物を建てた。"],
      ["put across", "伝える", "He put his ideas across clearly.", "彼は自分の考えをはっきり伝えた。"],
      ["put an end to", "終わらせる", "We must put an end to this waste.", "この無駄を終わらせなければならない。"],
    ],
  },
  {
    id: "give", classificationId: "verb", labelJa: "give 編", headWord: "give", emoji: "🎁",
    coreImage: "与える・差し出す",
    items: [
      ["give up", "諦める", "Don't give up on your dream.", "夢を諦めないで。"],
      ["give in", "屈服する", "He finally gave in to the pressure.", "彼はついに圧力に屈した。"],
      ["give out", "配る・尽きる", "Please give out these papers.", "これらのプリントを配ってください。"],
      ["give away", "無料で渡す・ばらす", "They gave away free samples.", "彼らは無料サンプルを配った。"],
      ["give back", "返す", "Please give back my book.", "本を返してください。"],
      ["give off", "発する", "The flower gives off a sweet smell.", "その花は甘い香りを放つ。"],
      ["give in to", "屈する", "Don't give in to temptation.", "誘惑に負けないで。"],
      ["give rise to", "引き起こす", "The news gave rise to many questions.", "そのニュースは多くの疑問を生んだ。"],
      ["give way", "道を譲る・崩れる", "Please give way to ambulances.", "救急車に道を譲ってください。"],
      ["give a hand", "手伝う", "Can you give me a hand?", "手伝ってくれる？"],
      ["give birth to", "産む", "She gave birth to a baby boy.", "彼女は男の子を産んだ。"],
      ["give credit", "功績を認める", "Give credit where credit is due.", "功績がある人にはきちんと認めよう。"],
      ["give it a try", "試してみる", "Just give it a try.", "とりあえず試してみて。"],
      ["give up on", "見限る", "I won't give up on you.", "君のことを見限らないよ。"],
      ["give notice", "予告する・辞表を出す", "He gave notice last week.", "彼は先週辞表を出した。"],
    ],
  },
  {
    id: "look", classificationId: "verb", labelJa: "look 編", headWord: "look", emoji: "👀",
    coreImage: "見る・様子を探る",
    items: [
      ["look after", "世話をする", "Can you look after my plants?", "植物の世話をしてくれる？"],
      ["look for", "探す", "I'm looking for my keys.", "鍵を探している。"],
      ["look forward to", "楽しみにする", "I look forward to seeing you.", "お会いできるのを楽しみにしています。"],
      ["look into", "調査する", "The police will look into the case.", "警察がその件を調べる。"],
      ["look up", "調べる・見上げる", "Look up the word in a dictionary.", "辞書でその単語を調べて。"],
      ["look up to", "尊敬する", "I look up to my teacher.", "先生を尊敬している。"],
      ["look down on", "見下す", "Don't look down on others.", "人を見下さないで。"],
      ["look out", "気をつける", "Look out for cars!", "車に気をつけて！"],
      ["look over", "ざっと見る", "Please look over this report.", "この報告書に目を通してください。"],
      ["look through", "目を通す", "I looked through the magazine.", "雑誌にざっと目を通した。"],
      ["look like", "〜のように見える", "It looks like rain.", "雨になりそうだ。"],
      ["look as if", "まるで〜のようだ", "You look as if you're tired.", "疲れてるみたいだね。"],
      ["look back", "振り返る", "Looking back, I have no regrets.", "振り返って後悔はない。"],
      ["look around", "見回す", "We looked around the museum.", "博物館を見回した。"],
      ["look ahead", "先を見る", "It's time to look ahead.", "先を見る時だ。"],
    ],
  },
  {
    id: "come", classificationId: "verb", labelJa: "come 編", headWord: "come", emoji: "🚶",
    coreImage: "来る・近づく・実現する",
    items: [
      ["come across", "出くわす", "I came across an old friend.", "昔の友人にばったり会った。"],
      ["come up with", "思いつく", "She came up with a great idea.", "彼女は素晴らしいアイデアを思いついた。"],
      ["come true", "実現する", "My dream came true.", "夢が叶った。"],
      ["come out", "出る・発売される", "The book comes out next month.", "その本は来月発売される。"],
      ["come in", "入る", "Please come in.", "どうぞ入ってください。"],
      ["come over", "立ち寄る", "Why don't you come over tonight?", "今夜うちに来ない？"],
      ["come along", "一緒に来る・順調に進む", "Come along with us!", "一緒に来て！"],
      ["come back", "戻る", "I'll come back soon.", "すぐに戻ります。"],
      ["come down", "下がる・降りてくる", "Prices have come down.", "値段が下がった。"],
      ["come from", "〜出身である", "Where do you come from?", "出身はどこですか？"],
      ["come on", "さあ・起きて", "Come on, we're late!", "ほら、遅刻するよ！"],
      ["come about", "起こる", "How did this problem come about?", "この問題はどうして起きたの？"],
      ["come into", "相続する・入る", "He came into a fortune.", "彼は財産を相続した。"],
      ["come to", "意識を取り戻す・合計する", "The bill came to 50 dollars.", "勘定は50ドルになった。"],
      ["come up", "話題に上がる", "Your name came up in the meeting.", "会議であなたの名前が出た。"],
    ],
  },
  {
    id: "go", classificationId: "verb", labelJa: "go 編", headWord: "go", emoji: "➡️",
    coreImage: "進む・変化する・続く",
    items: [
      ["go on", "続く・進む", "Please go on with your story.", "話を続けてください。"],
      ["go out", "外出する・消える", "Let's go out for dinner.", "外食しに行こう。"],
      ["go through", "経験する・調べる", "She went through a hard time.", "彼女はつらい時期を経験した。"],
      ["go over", "見直す", "Let's go over the plan again.", "計画をもう一度見直そう。"],
      ["go along with", "同意する", "I go along with your proposal.", "あなたの提案に賛成です。"],
      ["go ahead", "先に進む", "Go ahead and start without me.", "私を待たずに始めて。"],
      ["go back", "戻る", "I need to go back home.", "家に戻る必要がある。"],
      ["go by", "過ぎる", "Time goes by so fast.", "時間があっという間に過ぎる。"],
      ["go down", "下がる", "The temperature went down.", "気温が下がった。"],
      ["go up", "上がる", "Prices went up last year.", "去年物価が上がった。"],
      ["go without", "なしで済ませる", "I can't go without coffee.", "コーヒーなしではいられない。"],
      ["go for", "選ぶ・狙う", "I'll go for the blue one.", "青い方にするよ。"],
      ["go off", "鳴る・腐る", "The alarm went off at six.", "アラームが6時に鳴った。"],
      ["go after", "追う", "The police went after the thief.", "警察が泥棒を追った。"],
      ["go with", "合う・付き合う", "This tie goes with your shirt.", "このネクタイはシャツに合う。"],
    ],
  },
  {
    id: "set", classificationId: "verb", labelJa: "set 編", headWord: "set", emoji: "⚙️",
    coreImage: "定める・配置する",
    items: [
      ["set up", "設立する・準備する", "They set up a new company.", "彼らは新しい会社を設立した。"],
      ["set off", "出発する・引き起こす", "We set off early in the morning.", "朝早く出発した。"],
      ["set out", "出発する・着手する", "She set out to write a novel.", "彼女は小説を書くことに着手した。"],
      ["set aside", "取っておく", "Set aside some time for exercise.", "運動の時間を取っておいて。"],
      ["set back", "遅らせる", "The rain set back our plans.", "雨で予定が遅れた。"],
      ["set in", "始まる（悪いことが）", "Winter has set in.", "冬が始まった。"],
      ["set down", "書き留める", "Set down your ideas on paper.", "考えを紙に書き留めて。"],
      ["set free", "解放する", "They set the bird free.", "彼らは鳥を放した。"],
      ["set fire to", "放火する", "Someone set fire to the shed.", "誰かが物置に火をつけた。"],
      ["set an example", "手本を示す", "Teachers should set an example.", "教師は手本を示すべきだ。"],
      ["set the table", "食卓を整える", "Please set the table for dinner.", "夕食の準備でテーブルを整えて。"],
      ["set a record", "記録を出す", "She set a new world record.", "彼女は世界新記録を出した。"],
      ["set goals", "目標を立てる", "It's important to set goals.", "目標を立てることが大切だ。"],
      ["set the stage", "下地を作る", "This set the stage for success.", "これが成功の下地になった。"],
      ["set foot in", "足を踏み入れる", "I have never set foot in that city.", "その街には一度も行ったことがない。"],
    ],
  },
  {
    id: "keep", classificationId: "verb", labelJa: "keep 編", headWord: "keep", emoji: "🔒",
    coreImage: "保つ・続ける",
    items: [
      ["keep on", "続ける", "Keep on trying!", "挑戦し続けて！"],
      ["keep up", "維持する", "Keep up the good work.", "その調子で続けて。"],
      ["keep up with", "遅れずについていく", "It's hard to keep up with technology.", "技術の進歩についていくのは大変だ。"],
      ["keep away", "近づかない", "Keep away from the fire.", "火に近づかないで。"],
      ["keep out", "入れない", "Keep out of this room.", "この部屋に入らないで。"],
      ["keep off", "立ち入らない", "Keep off the grass.", "芝生に入らないで。"],
      ["keep from", "〜しないようにする", "I couldn't keep from laughing.", "笑わずにはいられなかった。"],
      ["keep in mind", "覚えておく", "Keep in mind that time is limited.", "時間が限られていることを覚えておいて。"],
      ["keep an eye on", "監視する", "Keep an eye on the baby.", "赤ちゃんから目を離さないで。"],
      ["keep in touch", "連絡を取る", "Let's keep in touch.", "連絡を取り合いましょう。"],
      ["keep secret", "秘密にする", "Please keep this secret.", "これは秘密にしてください。"],
      ["keep calm", "冷静でいる", "Keep calm and think clearly.", "冷静に、はっきり考えて。"],
      ["keep pace with", "歩調を合わせる", "She keeps pace with her classmates.", "彼女はクラスメートに遅れずについていく。"],
      ["keep to", "守る", "Please keep to the schedule.", "スケジュールを守ってください。"],
      ["keep going", "続ける", "Just keep going.", "そのまま続けて。"],
    ],
  },
  {
    id: "bring", classificationId: "verb", labelJa: "bring 編", headWord: "bring", emoji: "📦",
    coreImage: "持ってくる・もたらす",
    items: [
      ["bring up", "育てる・話題にする", "She brought up three children.", "彼女は3人の子供を育てた。"],
      ["bring about", "引き起こす", "The reform brought about change.", "改革が変化をもたらした。"],
      ["bring back", "思い出させる・戻す", "This song brings back memories.", "この歌は思い出を呼び起こす。"],
      ["bring out", "引き出す・発売する", "The teacher brings out the best in students.", "先生は生徒の良いところを引き出す。"],
      ["bring in", "導入する・収益を上げる", "The company brought in new rules.", "会社は新しい規則を導入した。"],
      ["bring down", "下げる・倒す", "They want to bring down prices.", "彼らは価格を下げたい。"],
      ["bring forward", "前倒しする", "The meeting was brought forward.", "会議が前倒しになった。"],
      ["bring together", "集める", "The event brought people together.", "その行事が人々を集めた。"],
      ["bring along", "連れて来る", "Bring along a friend if you like.", "よければ友達を連れて来て。"],
      ["bring to an end", "終わらせる", "The war was brought to an end.", "戦争は終結した。"],
      ["bring home", "痛感させる", "The story brought home the danger.", "その話が危険さを痛感させた。"],
      ["bring into line", "一致させる", "We need to bring costs into line.", "費用を適正に合わせる必要がある。"],
      ["bring into play", "活用する", "Bring all your skills into play.", "スキルをすべて活用して。"],
      ["bring on", "引き起こす", "Stress can bring on illness.", "ストレスは病気を引き起こすことがある。"],
      ["bring round", "意識を戻す・説得する", "They brought him round with cold water.", "冷水で彼の意識を戻した。"],
    ],
  },
  {
    id: "turn", classificationId: "verb", labelJa: "turn 編", headWord: "turn", emoji: "🔄",
    coreImage: "向きを変える・変化する",
    items: [
      ["turn on", "つける", "Please turn on the light.", "電気をつけてください。"],
      ["turn off", "消す", "Turn off your phone.", "スマホの電源を切って。"],
      ["turn up", "現れる・音を上げる", "He turned up late.", "彼は遅れて現れた。"],
      ["turn down", "断る・音を下げる", "She turned down the offer.", "彼女はその申し出を断った。"],
      ["turn into", "〜になる", "The caterpillar turned into a butterfly.", "青虫が蝶になった。"],
      ["turn out", "判明する・結果になる", "It turned out to be true.", "本当だと判明した。"],
      ["turn over", "裏返す・引き渡す", "Turn over the page.", "ページをめくって。"],
      ["turn around", "向きを変える・好転する", "The company turned around last year.", "会社は去年業績が好転した。"],
      ["turn away", "追い払う", "They turned away the visitors.", "彼らは訪問者を追い返した。"],
      ["turn back", "引き返す", "We had to turn back because of snow.", "雪のため引き返さなければならなかった。"],
      ["turn in", "提出する", "Please turn in your homework.", "宿題を提出してください。"],
      ["turn to", "頼る", "I turned to my friend for help.", "友人に助けを求めた。"],
      ["turn against", "敵対する", "Public opinion turned against him.", "世論が彼に不利になった。"],
      ["in turn", "順番に・その結果", "Each student spoke in turn.", "生徒が順番に話した。"],
      ["take a turn", "順番が回る・変化する", "Things took a turn for the better.", "事態が好転した。"],
    ],
  },
  {
    id: "break", classificationId: "verb", labelJa: "break 編", headWord: "break", emoji: "💥",
    coreImage: "壊す・中断する・突破する",
    items: [
      ["break down", "故障する・崩壊する", "My car broke down on the way.", "途中で車が故障した。"],
      ["break up", "別れる・解散する", "They broke up last month.", "彼らは先月別れた。"],
      ["break out", "勃発する", "A fire broke out in the kitchen.", "台所で火事が起きた。"],
      ["break into", "押し入る", "Someone broke into our house.", "誰かがうちに押し入った。"],
      ["break off", "折る・中断する", "She broke off the engagement.", "彼女は婚約を解消した。"],
      ["break through", "突破する", "Scientists broke through in research.", "科学者が研究でブレークスルーした。"],
      ["break away", "離脱する", "The horse broke away from the stable.", "馬が馬小屋から逃げた。"],
      ["break in", "慣らす・割り込む", "Don't break in while I'm talking.", "話している途中で割り込まないで。"],
      ["break the ice", "打ち解けるきっかけを作る", "A joke helped break the ice.", "ジョークが場を和ませた。"],
      ["break the news", "知らせる", "I had to break the bad news.", "悪い知らせを伝えなければならなかった。"],
      ["break a record", "記録を破る", "She broke the school record.", "彼女は学校記録を破った。"],
      ["break even", "収支ゼロになる", "The shop finally broke even.", "店はついに収支トントンになった。"],
      ["break free", "自由になる", "He broke free from the ropes.", "彼は縄から自由になった。"],
      ["break with", "関係を絶つ", "She broke with tradition.", "彼女は伝統と決別した。"],
      ["break one's word", "約束を破る", "Don't break your word.", "約束を破らないで。"],
    ],
  },
  {
    id: "call", classificationId: "verb", labelJa: "call 編", headWord: "call", emoji: "📞",
    coreImage: "呼ぶ・電話する・求める",
    items: [
      ["call off", "中止する", "They called off the game due to rain.", "雨のため試合は中止された。"],
      ["call on", "訪れる・求める", "I called on my teacher yesterday.", "昨日先生を訪ねた。"],
      ["call for", "要求する", "This job calls for patience.", "この仕事には忍耐が必要だ。"],
      ["call out", "大声で呼ぶ", "She called out my name.", "彼女が私の名前を呼んだ。"],
      ["call up", "電話する・召集する", "I'll call you up later.", "あとで電話するね。"],
      ["call back", "折り返し電話する", "Please call me back.", "折り返し電話してください。"],
      ["call in", "呼び入れる", "They called in an expert.", "専門家を呼び入れた。"],
      ["call at", "寄港する・立ち寄る", "The ship calls at this port.", "船はこの港に寄る。"],
      ["call it a day", "今日は終わりにする", "Let's call it a day.", "今日はここまでにしよう。"],
      ["call the shots", "采配を振る", "Who calls the shots here?", "ここでの采配は誰が振るの？"],
      ["call into question", "疑問を呈する", "The report called the plan into question.", "報告書はその計画に疑問を投げかけた。"],
      ["on call", "待機中の", "The doctor is on call tonight.", "その医者は今夜待機だ。"],
      ["call to mind", "思い出す", "That calls to mind my childhood.", "それで子供の頃を思い出す。"],
      ["call attention to", "注意を向けさせる", "I want to call attention to this issue.", "この問題に注意を向けたい。"],
      ["so-called", "いわゆる", "The so-called expert was wrong.", "いわゆる専門家は間違っていた。"],
    ],
  },
  {
    id: "run", classificationId: "verb", labelJa: "run 編", headWord: "run", emoji: "🏃‍♂️",
    coreImage: "走る・運営する・続く",
    items: [
      ["run out of", "〜がなくなる", "We ran out of milk.", "牛乳がなくなった。"],
      ["run into", "ばったり会う・ぶつかる", "I ran into my teacher downtown.", "街で先生にばったり会った。"],
      ["run away", "逃げる", "The dog ran away.", "犬が逃げた。"],
      ["run over", "ひく・ざっと目を通す", "A car almost ran over the cat.", "車が猫をひきそうになった。"],
      ["run through", "ざっとやる・使い果たす", "Let's run through the script.", "台本をざっと通そう。"],
      ["run after", "追いかける", "The kids ran after the ball.", "子供たちがボールを追いかけた。"],
      ["run across", "偶然見つける", "I ran across an old photo.", "古い写真を偶然見つけた。"],
      ["run for", "立候補する", "She will run for mayor.", "彼女は市長選に出馬する。"],
      ["run the risk", "危険を冒す", "You run the risk of failing.", "失敗する危険がある。"],
      ["in the long run", "長い目で見れば", "In the long run, it will help.", "長い目で見れば役に立つ。"],
      ["run late", "遅れている", "Sorry, I'm running late.", "ごめん、遅れそう。"],
      ["run smoothly", "順調に進む", "The event ran smoothly.", "行事は順調に進んだ。"],
      ["run a business", "事業を営む", "He runs a small cafe.", "彼は小さなカフェを営んでいる。"],
      ["run short", "不足する", "We're running short of time.", "時間が足りなくなってきた。"],
      ["run wild", "野放しになる", "Don't let your imagination run wild.", "想像を野放しにしないで。"],
    ],
  },
  {
    id: "hold", classificationId: "verb", labelJa: "hold 編", headWord: "hold", emoji: "🤲",
    coreImage: "持つ・保つ・開催する",
    items: [
      ["hold on", "待つ・つかまる", "Hold on a second.", "ちょっと待って。"],
      ["hold back", "抑える", "She held back her tears.", "彼女は涙をこらえた。"],
      ["hold up", "遅らせる・強盗する", "Traffic held us up.", "渋滞で遅れた。"],
      ["hold out", "持ちこたえる・差し出す", "Hold out your hand.", "手を出して。"],
      ["hold off", "延期する", "Let's hold off on that decision.", "その決断は先送りしよう。"],
      ["hold onto", "しがみつく", "Hold onto the railing.", "手すりにつかまって。"],
      ["hold against", "根に持つ", "Don't hold it against me.", "根に持たないで。"],
      ["get hold of", "捕まえる・入手する", "I couldn't get hold of him.", "彼と連絡が取れなかった。"],
      ["hold true", "当てはまる", "This rule still holds true.", "この規則は今も当てはまる。"],
      ["hold a meeting", "会議を開く", "We hold a meeting every Monday.", "毎週月曜に会議を開く。"],
      ["hold one's breath", "息を止める・固唾をのむ", "I held my breath underwater.", "水中で息を止めた。"],
      ["hold the line", "電話を切らずに待つ", "Please hold the line.", "そのままお待ちください。"],
      ["hold dear", "大切にする", "I hold this memory dear.", "この思い出を大切にしている。"],
      ["hold water", "理屈が通る", "That argument doesn't hold water.", "その議論は筋が通らない。"],
      ["hold responsible", "責任を負わせる", "Who do you hold responsible?", "誰に責任があると思う？"],
    ],
  },
  {
    id: "fall", classificationId: "verb", labelJa: "fall 編", headWord: "fall", emoji: "🍂",
    coreImage: "落ちる・陥る・減少する",
    items: [
      ["fall apart", "崩壊する", "Their plan fell apart.", "彼らの計画は崩壊した。"],
      ["fall behind", "遅れをとる", "Don't fall behind in class.", "授業で遅れをとらないで。"],
      ["fall for", "だまされる・恋する", "I fell for his story.", "彼の話にだまされた。"],
      ["fall out", "仲たがいする", "They fell out over money.", "お金のことで仲たがいした。"],
      ["fall through", "失敗する・流れになる", "The deal fell through.", "取引が流れた。"],
      ["fall down", "倒れる", "Be careful not to fall down.", "転ばないように気をつけて。"],
      ["fall into", "陥る", "He fell into a deep sleep.", "彼は深い眠りに落ちた。"],
      ["fall short", "足りない", "The results fell short of expectations.", "結果は期待に足りなかった。"],
      ["fall asleep", "眠る", "I fell asleep on the train.", "電車で眠ってしまった。"],
      ["fall in love", "恋に落ちる", "They fell in love at first sight.", "彼らは一目惚れした。"],
      ["fall back on", "頼りにする", "I have savings to fall back on.", "頼りにできる貯金がある。"],
      ["fall under", "〜に該当する", "This falls under safety rules.", "これは安全規則に該当する。"],
      ["fall to", "〜の番になる・取りかかる", "It fell to me to decide.", "決めるのは私の番になった。"],
      ["fall away", "減少する・離れる", "Support fell away over time.", "支持は次第に減った。"],
      ["fall due", "支払期限が来る", "The payment falls due next week.", "支払いは来週期限だ。"],
    ],
  },
  {
    id: "cut", classificationId: "verb", labelJa: "cut 編", headWord: "cut", emoji: "✂️",
    coreImage: "切る・削減する・中断する",
    items: [
      ["cut down", "削減する・切り倒す", "You should cut down on sugar.", "砂糖を減らした方がいい。"],
      ["cut off", "遮断する・電話を切る", "The call was cut off.", "電話が切れた。"],
      ["cut out", "切り抜く・やめる", "Cut out junk food.", "ジャンクフードはやめて。"],
      ["cut in", "割り込む", "Don't cut in line.", "列に割り込まないで。"],
      ["cut back", "切り詰める", "We need to cut back expenses.", "経費を切り詰める必要がある。"],
      ["cut across", "横切る", "We cut across the park.", "公園を横切った。"],
      ["cut through", "突き通す・近道する", "Cut through the alley.", "路地を抜けて近道して。"],
      ["cut short", "切り上げる", "The speech was cut short.", "スピーチが切り上げられた。"],
      ["cut corners", "手を抜く", "Don't cut corners on safety.", "安全で手を抜かないで。"],
      ["cut it out", "やめろ", "Cut it out!", "やめなさい！"],
      ["a cut above", "一枚上手", "She's a cut above the rest.", "彼女は他より一枚上手だ。"],
      ["cut both ways", "両刃の剣", "That argument cuts both ways.", "その議論は両刃の剣だ。"],
      ["cut to the chase", "要点に入る", "Let's cut to the chase.", "要点に入ろう。"],
      ["cut loose", "解放する・はしゃぐ", "They cut loose at the party.", "パーティーではしゃいだ。"],
      ["cut no ice", "効果がない", "His excuse cut no ice.", "彼の言い訳は通じなかった。"],
    ],
  },
  {
    id: "pick", classificationId: "verb", labelJa: "pick 編", headWord: "pick", emoji: "🤏",
    coreImage: "選ぶ・拾う・指摘する",
    items: [
      ["pick up", "拾う・迎えに行く・上達する", "I'll pick you up at the station.", "駅に迎えに行くよ。"],
      ["pick out", "選び出す", "Pick out a dress you like.", "好きなドレスを選んで。"],
      ["pick on", "いじめる", "Don't pick on younger kids.", "年下をいじめないで。"],
      ["pick at", "ちょこちょこ食べる", "She just picked at her food.", "彼女は少ししか食べなかった。"],
      ["pick up on", "気づく", "He quickly picked up on the mood.", "彼はすぐに空気を読んだ。"],
      ["pick apart", "細かく批判する", "Critics picked the film apart.", "批評家がその映画を細かく批判した。"],
      ["pick a fight", "喧嘩を売る", "Don't pick a fight with him.", "彼に喧嘩を売らないで。"],
      ["take your pick", "好きなものを選んで", "Take your pick of the desserts.", "デザートは好きなものを選んで。"],
      ["pick holes in", "あら探しをする", "He always picks holes in my plan.", "彼はいつも私の計画のあら探しをする。"],
      ["pick someone's brain", "知恵を借りる", "Can I pick your brain for a minute?", "少し知恵を借りてもいい？"],
      ["pick up the tab", "勘定を払う", "He picked up the tab.", "彼が勘定を払った。"],
      ["pick up speed", "加速する", "The train picked up speed.", "電車が加速した。"],
      ["pick up the pieces", "立て直す", "She picked up the pieces after the failure.", "失敗のあと彼女は立て直した。"],
      ["cherry-pick", "都合の良いものだけ選ぶ", "Don't cherry-pick the data.", "データの都合の良い部分だけ選ばないで。"],
      ["pick of the crop", "最高のもの", "This is the pick of the crop.", "これが最高のものだ。"],
    ],
  },
  {
    id: "about", classificationId: "preposition", labelJa: "about 編", headWord: "about", emoji: "💭",
    coreImage: "〜について・周囲・およそ",
    items: [
      ["about to", "まさに〜しようとしている", "I was about to leave.", "ちょうど出ようとしていた。"],
      ["how about", "〜はどう？", "How about some coffee?", "コーヒーはどう？"],
      ["what about", "〜はどうなの？", "What about your homework?", "宿題はどうしたの？"],
      ["just about", "ほぼ", "I'm just about ready.", "ほぼ準備できた。"],
      ["bring about", "引き起こす", "The law brought about change.", "その法律が変化を引き起こした。"],
      ["come about", "起こる", "How did that come about?", "どうしてそうなったの？"],
      ["go about", "取りかかる", "How should we go about this?", "どう取りかかればいい？"],
      ["set about", "着手する", "They set about cleaning.", "彼らは掃除に取りかかった。"],
      ["think about", "考える", "I'll think about it.", "考えておくよ。"],
      ["talk about", "話題にする", "We talked about the movie.", "映画の話をした。"],
      ["care about", "気にかける", "I care about you.", "君のことを気にかけている。"],
      ["crazy about", "〜に熱中して", "She's crazy about soccer.", "彼女はサッカーに熱中している。"],
      ["out and about", "外出して元気に", "He's out and about again.", "また元気に外出している。"],
      ["knock about", "あちこち歩き回る", "We knocked about the city.", "街をあちこち歩いた。"],
      ["see about", "手配する", "I'll see about tickets.", "チケットを手配するよ。"],
    ],
  },
  {
    id: "off", classificationId: "preposition", labelJa: "off 編", headWord: "off", emoji: "📴",
    coreImage: "離れて・電源オフ・休み",
    items: [
      ["off the record", "非公式に", "This is off the record.", "これは非公式の話だ。"],
      ["off duty", "非番で", "The officer is off duty.", "その警官は非番だ。"],
      ["day off", "休みの日", "Sunday is my day off.", "日曜は休みだ。"],
      ["take off", "離陸する・脱ぐ", "The plane took off.", "飛行機が離陸した。"],
      ["turn off", "消す", "Turn off the TV.", "テレビを消して。"],
      ["go off", "鳴る・腐る", "The alarm went off.", "アラームが鳴った。"],
      ["show off", "自慢する", "Don't show off.", "自慢しないで。"],
      ["call off", "中止する", "They called off the trip.", "旅行を中止した。"],
      ["put off", "延期する", "Don't put off your homework.", "宿題を先延ばししないで。"],
      ["set off", "出発する", "We set off at dawn.", "夜明けに出発した。"],
      ["pay off", "完済する・報われる", "Hard work pays off.", "努力は報われる。"],
      ["wear off", "薄れる", "The pain wore off.", "痛みが薄れた。"],
      ["break off", "中断する", "She broke off mid-sentence.", "彼女は途中で話をやめた。"],
      ["cut off", "遮断する", "They cut off the electricity.", "彼らは電気を止めた。"],
      ["better off", "より良い状態で", "You're better off without him.", "彼なしの方がいいよ。"],
    ],
  },
  // —— preposition ——
  {
    id: "in", classificationId: "preposition", labelJa: "in 編", headWord: "in", emoji: "🔹",
    coreImage: "〜の中・範囲・状態の内側",
    items: [
      ["in time", "間に合って", "We arrived just in time for the movie.", "映画にちょうど間に合って着いた。"],
      ["in charge of", "〜の責任者で", "She is in charge of the sales team.", "彼女は営業チームの責任者です。"],
      ["in fact", "実際", "In fact, I have never been there.", "実は、私はそこに行ったことがない。"],
      ["in common", "共通して", "We have a lot in common.", "私たちは共通点が多い。"],
      ["in the end", "結局", "In the end, everything worked out fine.", "結局、すべてうまくいった。"],
      ["in advance", "前もって", "Please book in advance.", "前もって予約してください。"],
      ["in case", "〜の場合に備えて", "Take an umbrella in case it rains.", "雨の場合に備えて傘を持って。"],
      ["in spite of", "〜にもかかわらず", "We went out in spite of the rain.", "雨にもかかわらず外に出た。"],
      ["in addition", "加えて", "In addition, we need more time.", "加えて、もっと時間が必要だ。"],
      ["in particular", "特に", "I love fruit, in particular apples.", "果物が好きで、特にりんごが好きだ。"],
      ["in public", "人前で", "Don't argue in public.", "人前で言い争わないで。"],
      ["in private", "内緒で", "Can we talk in private?", "内緒で話せますか？"],
      ["in general", "一般に", "In general, people like holidays.", "一般に、人は休みが好きだ。"],
      ["in detail", "詳細に", "Explain it in detail.", "詳しく説明して。"],
      ["in a hurry", "急いで", "I'm in a hurry.", "急いでいるんです。"],
      ["in touch", "連絡を取って", "Stay in touch.", "連絡を取ってね。"],
      ["in vain", "無駄に", "All my efforts were in vain.", "努力はすべて無駄だった。"],
      ["in favor of", "賛成して", "I'm in favor of the plan.", "その計画に賛成です。"],
      ["in terms of", "〜の点では", "In terms of price, it's cheap.", "価格の点では安い。"],
      ["in the long run", "長い目で見れば", "Exercise helps in the long run.", "運動は長い目で見れば役立つ。"],
    ],
  },
  {
    id: "on", classificationId: "preposition", labelJa: "on 編", headWord: "on", emoji: "🔸",
    coreImage: "〜の上・接触・進行中",
    items: [
      ["on time", "時間通りに", "The train arrived on time.", "電車は時間通りに到着した。"],
      ["on purpose", "わざと", "I didn't do it on purpose.", "わざとやったわけじゃない。"],
      ["on average", "平均して", "On average, I sleep seven hours.", "平均して7時間眠ります。"],
      ["on the other hand", "一方で", "It's expensive. On the other hand, it's high quality.", "高い。一方で、品質は良い。"],
      ["on behalf of", "〜を代表して", "I speak on behalf of the team.", "チームを代表して話します。"],
      ["on foot", "徒歩で", "I go to school on foot.", "歩いて学校に行く。"],
      ["on sale", "特売で", "These shoes are on sale.", "この靴は特売だ。"],
      ["on duty", "勤務中", "The nurse is on duty tonight.", "その看護師は今夜勤務だ。"],
      ["on fire", "燃えている", "The building was on fire.", "建物が燃えていた。"],
      ["on hold", "保留中", "Your call is on hold.", "お電話は保留中です。"],
      ["on the way", "途中で", "I'm on the way to the station.", "駅に向かう途中です。"],
      ["on second thought", "考え直すと", "On second thought, I'll stay.", "考え直すと、残ることにする。"],
      ["on one's own", "自力で", "She did it on her own.", "彼女は自力でやった。"],
      ["on the rise", "上昇中", "Prices are on the rise.", "物価は上昇中だ。"],
      ["on the whole", "全体として", "On the whole, it was fun.", "全体として楽しかった。"],
      ["on account of", "〜のせいで", "The game was canceled on account of rain.", "雨のため試合は中止された。"],
      ["on the contrary", "それどころか", "I'm not tired. On the contrary, I'm excited.", "疲れてない。それどころかワクワクしている。"],
      ["on edge", "神経質で", "I've been on edge all day.", "一日中そわそわしている。"],
      ["on cloud nine", "有頂天で", "She was on cloud nine after the news.", "その知らせで彼女は有頂天だった。"],
      ["on the spot", "その場で", "He was hired on the spot.", "彼はその場で採用された。"],
    ],
  },
  {
    id: "at", classificationId: "preposition", labelJa: "at 編", headWord: "at", emoji: "🎯",
    coreImage: "一点・状態・動作の対象",
    items: [
      ["at least", "少なくとも", "At least try once.", "少なくとも一度は試して。"],
      ["at most", "せいぜい", "It costs 10 dollars at most.", "せいぜい10ドルだ。"],
      ["at once", "すぐに", "Come here at once!", "すぐにここに来て！"],
      ["at all", "全く（否定で）", "I don't mind at all.", "全く構いません。"],
      ["at first", "最初は", "At first, I was nervous.", "最初は緊張した。"],
      ["at last", "ついに", "At last, we arrived.", "ついに到着した。"],
      ["at present", "現在", "At present, he lives in Tokyo.", "現在、彼は東京に住んでいる。"],
      ["at risk", "危険にさらされて", "The species is at risk.", "その種は危険にさらされている。"],
      ["at stake", "危機に瀕して", "Our future is at stake.", "私たちの未来がかかっている。"],
      ["at random", "無作為に", "Names were chosen at random.", "名前が無作為に選ばれた。"],
      ["at ease", "くつろいで", "Make yourself at ease.", "くつろいでください。"],
      ["at a loss", "途方に暮れて", "I was at a loss for words.", "言葉が出てこなかった。"],
      ["at the moment", "今のところ", "I'm busy at the moment.", "今のところ忙しいです。"],
      ["at times", "時々", "At times, I feel lonely.", "時々、孤独を感じる。"],
      ["good at", "〜が得意", "She's good at math.", "彼女は数学が得意だ。"],
    ],
  },
  {
    id: "for", classificationId: "preposition", labelJa: "for 編", headWord: "for", emoji: "🎁",
    coreImage: "目的・期間・交換・向け",
    items: [
      ["for example", "例えば", "I like fruits, for example apples.", "果物が好きで、例えばりんご。"],
      ["for instance", "例えば", "Take Japan, for instance.", "例えば日本を見てみよう。"],
      ["for good", "永久に", "He left the town for good.", "彼はその町を永久に去った。"],
      ["for now", "当分の間", "This will do for now.", "当分これで大丈夫。"],
      ["for sure", "確かに", "I know that for sure.", "それは確かに知っている。"],
      ["for free", "無料で", "You can download it for free.", "無料でダウンロードできる。"],
      ["for a while", "しばらく", "Let's rest for a while.", "しばらく休もう。"],
      ["for the sake of", "〜のために", "Do it for the sake of your health.", "健康のためにやって。"],
      ["for fear of", "〜を恐れて", "He spoke quietly for fear of waking the baby.", "赤ちゃんを起こすのを恐れて静かに話した。"],
      ["ask for", "求める", "He asked for help.", "彼は助けを求めた。"],
      ["look for", "探す", "I'm looking for a job.", "仕事を探している。"],
      ["wait for", "待つ", "Please wait for me.", "待ってて。"],
      ["care for", "世話をする・好む", "She cares for her grandmother.", "彼女は祖母の世話をしている。"],
      ["apply for", "申し込む", "I applied for the position.", "その職に申し込んだ。"],
      ["responsible for", "〜の責任がある", "Who is responsible for this?", "これの責任者は誰？"],
    ],
  },
  {
    id: "by", classificationId: "preposition", labelJa: "by 編", headWord: "by", emoji: "✋",
    coreImage: "手段・付近・期限・差",
    items: [
      ["by chance", "偶然に", "We met by chance.", "偶然会った。"],
      ["by far", "はるかに", "This is by far the best.", "これがはるかに一番だ。"],
      ["by heart", "暗記して", "Learn this poem by heart.", "この詩を暗記して。"],
      ["by mistake", "間違って", "I deleted the file by mistake.", "間違ってファイルを消した。"],
      ["by oneself", "一人で", "She did it by herself.", "彼女は一人でやった。"],
      ["by the way", "ところで", "By the way, how's your family?", "ところで、ご家族は元気？"],
      ["by means of", "〜によって", "We communicate by means of email.", "メールで連絡を取る。"],
      ["by virtue of", "〜のおかげで", "He succeeded by virtue of hard work.", "彼は努力のおかげで成功した。"],
      ["little by little", "少しずつ", "Little by little, I improved.", "少しずつ上達した。"],
      ["one by one", "一つずつ", "Check them one by one.", "一つずつ確認して。"],
      ["day by day", "日ごとに", "Day by day, she got better.", "日ごとに彼女は良くなった。"],
      ["by all means", "ぜひ", "By all means, come in.", "ぜひ入ってください。"],
      ["by no means", "決して〜ない", "It is by no means easy.", "決して簡単ではない。"],
      ["stand by", "待機する・支持する", "Please stand by.", "そのままお待ちください。"],
      ["pass by", "通り過ぎる", "Time passes by quickly.", "時間はあっという間に過ぎる。"],
    ],
  },
  {
    id: "with", classificationId: "preposition", labelJa: "with 編", headWord: "with", emoji: "🤝",
    coreImage: "一緒・手段・付帯状況",
    items: [
      ["with regard to", "〜に関して", "With regard to your question...", "ご質問に関して…"],
      ["with respect to", "〜について", "With respect to cost, it's fine.", "費用については問題ない。"],
      ["along with", "〜と一緒に", "Bring your passport along with you.", "パスポートも一緒に持ってきて。"],
      ["together with", "〜と共に", "She came together with her sister.", "彼女は妹と一緒に来た。"],
      ["deal with", "対処する", "How do you deal with stress?", "ストレスにどう対処する？"],
      ["cope with", "うまくやりくりする", "He coped with the pressure well.", "彼はプレッシャーにうまく対処した。"],
      ["agree with", "同意する", "I agree with you.", "賛成です。"],
      ["catch up with", "追いつく", "I need to catch up with my work.", "仕事に追いつかないと。"],
      ["come up with", "思いつく", "Did you come up with a plan?", "計画は思いついた？"],
      ["keep up with", "遅れずについていく", "Keep up with the class.", "授業についていって。"],
      ["put up with", "我慢する", "I can't put up with this heat.", "この暑さには耐えられない。"],
      ["get along with", "うまくやる", "She gets along with everyone.", "彼女は誰とでもうまくやる。"],
      ["be filled with", "〜でいっぱい", "The room was filled with laughter.", "部屋は笑い声でいっぱいだった。"],
      ["be satisfied with", "満足している", "Are you satisfied with the result?", "結果に満足していますか？"],
      ["in accordance with", "〜に従って", "Act in accordance with the rules.", "規則に従って行動して。"],
    ],
  },
  {
    id: "out", classificationId: "preposition", labelJa: "out 編", headWord: "out", emoji: "🚪",
    coreImage: "外へ・終了・明らか",
    items: [
      ["out of", "〜から外へ・〜切れ", "We're out of sugar.", "砂糖が切れている。"],
      ["out of date", "時代遅れの", "This map is out of date.", "この地図は古い。"],
      ["out of order", "故障して", "The elevator is out of order.", "エレベーターが故障している。"],
      ["out of control", "制御不能で", "The fire got out of control.", "火の手が制御不能になった。"],
      ["out of the blue", "突然", "He called me out of the blue.", "彼が突然電話してきた。"],
      ["out of breath", "息切れして", "I was out of breath after the run.", "走ったあと息切れした。"],
      ["out of sight", "見えないところに", "Out of sight, out of mind.", "去る者は日々に疎し。"],
      ["find out", "発見する", "I found out the truth.", "真実を知った。"],
      ["figure out", "理解する", "I can't figure out this math.", "この数学がわからない。"],
      ["point out", "指摘する", "She pointed out my mistake.", "彼女が私のミスを指摘した。"],
      ["carry out", "実行する", "We carried out the plan.", "計画を実行した。"],
      ["work out", "うまくいく・運動する", "Things will work out.", "うまくいくよ。"],
      ["check out", "確認する・チェックアウト", "Check out this website.", "このサイトをチェックして。"],
      ["run out", "なくなる", "Time is running out.", "時間がなくなってきた。"],
      ["turn out", "判明する", "It turned out fine.", "結局うまくいった。"],
    ],
  },
  {
    id: "up", classificationId: "preposition", labelJa: "up 編", headWord: "up", emoji: "⬆️",
    coreImage: "上へ・完了・増加",
    items: [
      ["up to", "〜まで・〜次第", "It's up to you.", "君次第だよ。"],
      ["up to date", "最新の", "Keep your software up to date.", "ソフトを最新にしておいて。"],
      ["give up", "諦める", "Never give up.", "決して諦めるな。"],
      ["wake up", "起きる", "I wake up early.", "早く起きる。"],
      ["grow up", "育つ", "I grew up in Osaka.", "大阪で育った。"],
      ["hurry up", "急ぐ", "Hurry up!", "急いで！"],
      ["show up", "現れる", "He didn't show up.", "彼は現れなかった。"],
      ["end up", "結局〜になる", "We ended up staying home.", "結局家にいた。"],
      ["make up", "仲直りする・構成する", "They made up after the fight.", "喧嘩のあと仲直りした。"],
      ["pick up", "拾う・迎えに行く", "I'll pick you up at six.", "6時に迎えに行くよ。"],
      ["set up", "設置する", "Can you set up the tent?", "テントを張れる？"],
      ["clean up", "きれいにする", "Please clean up your room.", "部屋を片付けて。"],
      ["catch up", "追いつく", "I need to catch up on sleep.", "睡眠不足を取り戻さないと。"],
      ["cheer up", "元気を出す", "Cheer up! It'll be okay.", "元気出して！大丈夫だよ。"],
      ["shut up", "黙る（失礼）", "Just shut up and listen.", "黙って聞いて。"],
    ],
  },
  // —— other ——
  {
    id: "as", classificationId: "other", labelJa: "as 表現", headWord: "as", emoji: "↔️",
    coreImage: "比較・役割・同時",
    items: [
      ["as well", "〜もまた", "I'd like coffee as well.", "コーヒーもください。"],
      ["as well as", "〜だけでなく", "She speaks English as well as Japanese.", "彼女は日本語だけでなく英語も話す。"],
      ["as soon as", "〜するとすぐに", "Call me as soon as you arrive.", "着いたらすぐに電話して。"],
      ["as long as", "〜である限り", "You can stay as long as you like.", "好きなだけいていいよ。"],
      ["as far as", "〜する限り", "As far as I know, he's fine.", "私の知る限り、彼は元気だ。"],
      ["as if", "まるで〜のように", "He talks as if he knows everything.", "何でも知っているかのように話す。"],
      ["as though", "あたかも〜のように", "She looked as though she had cried.", "泣いたあとみたいだった。"],
      ["as for", "〜については", "As for me, I agree.", "私については賛成です。"],
      ["as to", "〜に関して", "As to the schedule, it's flexible.", "予定については柔軟です。"],
      ["as usual", "いつものように", "He was late as usual.", "いつものように彼は遅れた。"],
      ["as a result", "その結果", "As a result, we won.", "その結果、勝った。"],
      ["as a matter of fact", "実は", "As a matter of fact, I was there.", "実は、そこにいたんだ。"],
      ["such as", "例えば", "I like sports such as soccer.", "サッカーなどのスポーツが好きだ。"],
      ["as...as", "〜と同じくらい", "She is as tall as her brother.", "彼女は兄と同じくらい背が高い。"],
      ["not as...as", "〜ほど〜ない", "It's not as hard as I thought.", "思ったほど難しくない。"],
      ["as soon as possible", "できるだけ早く", "Please reply as soon as possible.", "できるだけ早く返信してください。"],
      ["as of", "〜時点で", "As of today, the rule changes.", "本日より規則が変わります。"],
      ["as opposed to", "〜とは対照的に", "Tea, as opposed to coffee, is milder.", "コーヒーと対照的に、お茶は穏やかだ。"],
      ["as follows", "次の通り", "The rules are as follows.", "規則は次の通りです。"],
      ["so as to", "〜するために", "He left early so as to catch the train.", "電車に乗るため早く出た。"],
    ],
  },
  {
    id: "time", classificationId: "other", labelJa: "時間の表現", headWord: "time", emoji: "⏰",
    coreImage: "時間に関わる慣用表現",
    items: [
      ["from time to time", "時々", "I visit my parents from time to time.", "時々両親を訪ねる。"],
      ["all the time", "いつも", "He's busy all the time.", "彼はいつも忙しい。"],
      ["at the same time", "同時に", "Don't talk at the same time.", "同時に話さないで。"],
      ["for the time being", "当分の間", "Stay here for the time being.", "当分ここにいて。"],
      ["in no time", "すぐに", "We'll finish in no time.", "すぐに終わるよ。"],
      ["once upon a time", "昔々", "Once upon a time, there was a king.", "昔々、王様がいました。"],
      ["kill time", "暇をつぶす", "I killed time at the cafe.", "カフェで暇をつぶした。"],
      ["have a hard time", "苦労する", "I had a hard time finding the place.", "場所を見つけるのに苦労した。"],
      ["take one's time", "ゆっくりする", "Take your time.", "ゆっくりでいいよ。"],
      ["ahead of time", "予定より早く", "We arrived ahead of time.", "予定より早く着いた。"],
      ["behind the times", "時代遅れ", "That idea is behind the times.", "その考えは時代遅れだ。"],
      ["of all time", "史上", "It's the best movie of all time.", "史上最高の映画だ。"],
      ["time flies", "光陰矢の如し", "Time flies when you're having fun.", "楽しいと時間があっという間。"],
      ["better late than never", "遅くてもやらないよりマシ", "Better late than never.", "遅くてもやらないよりいい。"],
      ["in due time", "時機が来れば", "You'll understand in due time.", "時機が来ればわかるよ。"],
    ],
  },
  {
    id: "body", classificationId: "other", labelJa: "体の慣用句", headWord: "body", emoji: "🧍",
    coreImage: "体の部位を使った表現",
    items: [
      ["by heart", "暗記して", "I know the song by heart.", "その歌は暗記している。"],
      ["lose heart", "がっかりする", "Don't lose heart.", "がっかりしないで。"],
      ["take heart", "元気を出す", "Take heart from your progress.", "上達を励みに元気を出して。"],
      ["heart and soul", "心を込めて", "She put her heart and soul into it.", "彼女は心を込めて取り組んだ。"],
      ["learn by heart", "暗記する", "Learn these words by heart.", "これらの単語を暗記して。"],
      ["keep an eye on", "見張る", "Keep an eye on your bag.", "かばんに気をつけて。"],
      ["catch one's eye", "目につく", "The red dress caught my eye.", "赤いドレスが目についた。"],
      ["see eye to eye", "意見が合う", "We don't always see eye to eye.", "いつも意見が合うわけじゃない。"],
      ["turn a blind eye", "見て見ぬふり", "Don't turn a blind eye to bullying.", "いじめを見て見ぬふりしないで。"],
      ["lend an ear", "耳を傾ける", "He lent an ear to my worries.", "彼は私の悩みに耳を傾けた。"],
      ["play it by ear", "臨機応変にやる", "We'll play it by ear.", "臨機応変にやろう。"],
      ["face to face", "対面で", "I'd rather talk face to face.", "対面で話したい。"],
      ["lose face", "面目を失う", "He doesn't want to lose face.", "彼は面目を失いたくない。"],
      ["save face", "面目を保つ", "The deal helped him save face.", "その取引で彼は面目を保てた。"],
      ["on one's feet", "元気で・立って", "She's back on her feet.", "彼女は元気を取り戻した。"],
      ["cold feet", "怖気づく", "He got cold feet before the wedding.", "結婚式前に怖気づいた。"],
      ["pull one's leg", "からかう", "Are you pulling my leg?", "からかってるの？"],
      ["cost an arm and a leg", "とても高い", "That car costs an arm and a leg.", "その車はとても高い。"],
      ["give a hand", "手伝う", "Can you give me a hand?", "手伝って？"],
      ["keep one's head", "冷静でいる", "Keep your head in an emergency.", "緊急時は冷静でいて。"],
    ],
  },
  {
    id: "common", classificationId: "other", labelJa: "よく使う定型", headWord: "common", emoji: "⭐",
    coreImage: "会話で頻出の決まり文句",
    items: [
      ["of course", "もちろん", "Of course I will help you.", "もちろん手伝うよ。"],
      ["no wonder", "当たり前だ", "No wonder you're tired.", "疲れるのも当然だよ。"],
      ["no matter", "〜でも", "No matter what happens, stay calm.", "何があっても冷静でいて。"],
      ["rather than", "〜よりもむしろ", "I'd walk rather than wait.", "待つくらいなら歩いた方がいい。"],
      ["instead of", "〜の代わりに", "I drank tea instead of coffee.", "コーヒーの代わりにお茶を飲んだ。"],
      ["because of", "〜のせいで", "The game was canceled because of rain.", "雨のせいで試合は中止になった。"],
      ["thanks to", "〜のおかげで", "Thanks to you, we won.", "あなたのおかげで勝てた。"],
      ["due to", "〜が原因で", "The delay was due to traffic.", "遅れは渋滞が原因だった。"],
      ["according to", "〜によると", "According to the news, it will rain.", "ニュースによると雨が降る。"],
      ["in order to", "〜するために", "I study in order to pass.", "合格するために勉強する。"],
      ["so that", "〜するように", "Speak slowly so that I can understand.", "わかるようにゆっくり話して。"],
      ["even if", "たとえ〜でも", "Even if it rains, I'll go.", "たとえ雨でも行く。"],
      ["even though", "〜なのに", "Even though I was tired, I worked.", "疲れていたのに働いた。"],
      ["as soon as", "〜するとすぐ", "Call as soon as you can.", "できるだけ早く電話して。"],
      ["whether or not", "〜かどうか", "I don't know whether or not he'll come.", "彼が来るかはわからない。"],
      ["used to", "以前は〜したものだ", "I used to play soccer.", "昔はサッカーをしていた。"],
      ["be used to", "〜に慣れている", "I'm used to waking up early.", "早起きには慣れている。"],
      ["would rather", "むしろ〜したい", "I would rather stay home.", "むしろ家にいたい。"],
      ["had better", "〜した方がいい", "You had better hurry.", "急いだ方がいい。"],
      ["not only...but also", "〜だけでなく〜も", "She is not only kind but also smart.", "彼女は親切なだけでなく賢い。"],
    ],
  },
];

const groups = [];
const items = [];

for (const g of GROUP_DEFS) {
  groups.push({
    id: g.id,
    classificationId: g.classificationId,
    labelJa: g.labelJa,
    headWord: g.headWord,
    emoji: g.emoji,
    coreImage: g.coreImage,
  });
  g.items.forEach(([en, ja, exampleEn, exampleJa], i) => {
    items.push({
      id: `${g.id}-${i + 1}`,
      groupId: g.id,
      en,
      ja,
      exampleEn,
      exampleJa,
    });
  });
}

const out = { classifications, groups, items };
const outPath = join(__dirname, "..", "data", "idioms", "idioms.json");
writeFileSync(outPath, JSON.stringify(out, null, 2) + "\n");

console.log("groups", groups.length);
console.log("items", items.length);
console.log(
  "by class",
  Object.fromEntries(
    classifications.map((c) => [
      c.id,
      items.filter((i) => groups.find((g) => g.id === i.groupId)?.classificationId === c.id).length,
    ]),
  ),
);
